# https://distribution.github.io/distribution/about/configuration/#list-of-configuration-options
version: 0.1
log:
  # [error, warn, info, debug]
  level: info
  formatter: json
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: redis
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
redis:
  addrs: [redis:6379]
  maxidleconns: 16
  poolsize: 64
  connmaxidletime: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
